modLoader = "javafml"
loaderVersion = "[${forge_version},)"
#issueTrackerURL = ""
license = "GNU GPLv3"

[[mods]]
modId = "trackmap"
version = "${version}"
displayName = "Track Map"
authors = "Rabbitminers"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
logoFile = "icon.png"

[[dependencies.trackmap]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.trackmap]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.trackmap]]
modId="create"
mandatory=true
versionRange="${create_version}"
ordering="NONE"
side="BOTH"